### ISSUE TITLE
Centering the Indicators seem to be ignored

### ISSUE THREAD

**Issue by houmie** [ninjaprox/LoaderUI#11]
I'm not sure if this is a new bug:

I don't seem to be able to centre them horizontally.

```
HStack {
    Spacer()
    BallPulse()
    Spacer()
}

```

<img width="458" alt="Screenshot 2024-05-06 at 11 07 54" src="https://github.com/ninjaprox/LoaderUI/assets/1832933/2809f1b2-c054-434a-b408-cbdc89574502">

It remains always left aligned.

Am I missing something?

**Comment by ninjaprox** [comment]
Is the entire body of the view? In the above example, `Spacer` doesn't seem to be necessary to center the indicator horizontally. I try the example and the indicator takes full width of the screen

**Comment by houmie** [comment]
I figured it out. :-) 

It needs the frame, otherwise you get to see what I posted above. Quite strange.
```
VStack {
    Spacer()
    BallPulse().frame(width: 80, height: 80)
    Spacer()
}
```

**Comment by ninjaprox** [comment]
Is `VStack` or `HStack` a child of another view? Could you share the entire view body? I guess it's not the entire body of the view, otherwise you won't have the issue and don't need `Spacer` to center the indicator.
