### ISSUE TITLE
Animation only work once

### ISSUE THREAD

**Issue by SiddharthChoudhary** [ninjaprox/LoaderUI#4]
I am trying to leverage the LoaderUI in my iOS application in Swift UI and I have a simple codebase where I am doing
 
```
VStack{
BallPulse()
}
```
but now what happens is that it loads only once and that is it. It just sits there like an image. Can someone help me with what exactly could be a reason behind this?
Is this something which I have to do in my codebase, like providing an animation support cause I don't think I need to do that. Or I am leveraging the LoaderUI library the wrong way?

Thanks,

**Comment by ninjaprox** [comment]
I guess it's due to some changes in iOS version later 13.0. Could you try [0.1.1](https://github.com/ninjaprox/LoaderUI/tree/0.1.1) version if it's still an issue?
