### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by houmie** [ninjaprox/LoaderUI#8]
It would be a shame killing off this project.

There are a couple of PRs waiting and there needs to be a way to slow down the animations, please.

**Comment by ninjaprox** [comment]
I start to work on the project again recently, more fixes are coming. Unfortunately, slowing down animations mightn't be added.

**Comment by houmie** [comment]
That would be amazing to get an updated version. Thank you.

**Comment by houmie** [comment]
@ninjaprox Thanks for the new release. Amazing!

Could you please add a few lines in the README how to use this in SwiftUI, please?

UPDATE:
Actually it's as simple as adding something like BallPulse() in the view.
I just tested it on iOS 17. It works very well.
